name: Build, Push, and Update
permissions:
  id-token: write # required to use OIDC authentication
  contents: write # required
  actions: read
  security-events: write
  statuses: write
on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t http-server:go-${{ github.sha }} .
        env:
          DOCKER_CLI: docker

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'http-server:go-${{ github.sha }}'
          format: 'table'
          # format: 'table, template'
          # template: '@/contrib/sarif.tpl'
          # exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          # output: 'trivy-results-docker.sarif'
          severity: 'CRITICAL,HIGH'

          
      - name: Login to ECR
        id: ecr
        uses: jwalton/gh-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
      - name: Push to ECR
        run: |
          docker tag http-server:go-${{ github.sha }} 202334581163.dkr.ecr.us-east-1.amazonaws.com/http-server:go-${{ github.sha }}
          docker push 202334581163.dkr.ecr.us-east-1.amazonaws.com/http-server:go-${{ github.sha }}

  update:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: helm-charts
          
      - name: Update Helm Chart
        run: |
          yq eval -i '.image.tag = "go-${{ github.sha }}"' http-server/values.yaml
          echo "simple go app image tag updated"

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.REPO_PUSH_KEY }}
          commit_message: update simple-go-app image tag to go-${{ github.sha }}